### ISSUE TITLE
Adding C++ programs with DSA

### ISSUE THREAD

**Issue by gandhi25samar** [TAbhay/Hacktoberfest-2023#31]
I would like to take up this issue
please assign me with this @TAbhay and add the hacktoberfest label to this.

**Comment by bhaveshgarg2000** [comment]
Please assign this issue to me @gandhi25samar

**Comment by TAbhay** [comment]
@gandhi25samar @bhaveshgarg2000   Anyone can take it
Put it in algorithms/or create Languages directory 
Also move java folder into Languages directory
Languages/cpp
Languages/java
