### ISSUE TITLE
Adding different beginner friendly tasks in issues

### ISSUE THREAD

**Issue by TAbhay** [TAbhay/Hacktoberfest-2023#37]
**Create a New Issue:**
Click on the "Issues" tab at the top of your repository.
Then, click the green "New Issue" button.

**Give Your Issue a Title:**
Make it clear that this issue is for adding beginner-friendly tasks. For example, you can title it "Add Beginner-Friendly Tasks.

**Write a Description:**
In the description, explain the purpose of the issue.
Label and Assign: 

You can assign the issue to yourself or someone else.

**`Add Binary Search Algorithm Implementation in [Language of Choice]`
`Implement a Bubble Sort Algorithm in [Language of Choice]`
`Create a Fibonacci Number Generator in [Language of Choice]`
`Develop a Simple Calculator Application in [Language of Choice]`
`Write a Function to Check for Prime Numbers in [Language of Choice]`
`Build a Basic Tic-Tac-Toe Game in [Language of Choice]`
`Add a Factorial Calculator Function in [Language of Choice]`
`Implement a Palindrome Checker in [Language of Choice]`
`Create a Guess the Number Game in [Language of Choice]`
`Build a Basic To-Do List Application in [Language of Choice]`
`Add a Linear Search Algorithm in [Language of Choice]`
`Implement Insertion Sort in [Language of Choice]`
`Write a Function to Reverse a String in [Language of Choice]`
`Develop a Temperature Converter in [Language of Choice]`
`Create a Simple Alarm Clock Application in [Language of Choice]`
`Implement Merge Sort in [Language of Choice]`
`Add a GCD (Greatest Common Divisor) Calculator in [Language of Choice]`
`Write a Function to Calculate Factorial Using Recursion in [Language of Choice]`
`Build a Basic Chat Application in [Language of Choice]`
`Create a BMI (Body Mass Index) Calculator in [Language of Choice]`
`Implement a Queue Data Structure in [Language of Choice]`
`Add a Stack Data Structure in [Language of Choice]`
`Develop a Basic Hangman Game in [Language of Choice]`
`Write a Function to Calculate Exponents in [Language of Choice]`**

**Comment by TAbhay** [comment]
@VedantpD @gandhi25samar Guys can you create new issues ?

**Comment by VedantpD** [comment]
@TAbhay Yep, I can create few issues , but it says your repo is now excluded from hacktoberfest as it does not follow the values of the event.

**Comment by TAbhay** [comment]
@VedantpD BAD REPO : Looks like someone reported XD
